spring:
  application:
    name: calorietracker

  datasource:
    url: jdbc:postgresql://localhost:5432/calorietracker
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  

server:
  port: 8080

jwt:
  secret: Y2Fsb3JpZS10cmFja2VyLXN1cGVyLXNlY3JldC1rZXktMjAyNi1rYXJhbi1kZXY=
  expiration: 86400000